NAME = libft.a

CFLAGS = -Wall -Wextra -Werror

CC = gcc

SRCS = ft_bzero.c ft_isdigit.c ft_memset.c ft_strlen.c ft_toupper.c \
       ft_isalnum.c ft_isprint.c ft_strchr.c ft_strncmp.c ft_isalpha.c \
       ft_memcpy.c ft_strlcat.c ft_strrchr.c ft_isascii.c ft_memmove.c \
       ft_strlcpy.c ft_tolower.c

# FALTA 5 FUNCOES DA PRIMEIRA PARTE  !!!

OBJ = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all	
